baseURL: "https://dacbarbosa.github.io/"
title: Daniel Barbosa
pagination:
  pagerSize: 20
theme: PaperMod

ignoreLogs:
  - warning-partial-superfluous-prefix

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main: []

params:
    description: "PhD candidate in Economics at the University of Oxford (Nuffield College). Research in macroeconomics, environmental economics, finance, and international economics."
    author: Daniel A.C. Barbosa
    images:
      - "photo-dacb.jpg"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    env: production
    profileMode:
          enabled: true
          title: Daniel A.C. Barbosa
          subtitle: "PhD candidate in Economics at the University of Oxford and Nuffield College. \n

          My research focuses on macroeconomics, environmental and resource economics, finance, and international economics. \n

          In Summer 2026, I will be joining the **Bank of England** as a PhD Intern at the **Monetary Policy Strategy Division**. \n

          [Download my CV](/cv-barbosa.pdf)"
          imageUrl: "photo-dacb.jpg"
          imageWidth: 320
          imageHeight: 400
          imageTitle: Daniel A.C. Barbosa

    socialIcons:
        - name: cv
          url: cv-barbosa.pdf
        - name: Email
          url: mailto:daniel.barbosa@economics.ox.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=K5aOUegAAAAJ&hl
        - name: GitHub
          url: https://github.com/dacbarbosa
        - name: x
          url: https://x.com/barbosa_dac

    assets:
        disableScrollBarStyle: true
        favicon: "oxford-crest.png"
        favicon16x16: "oxford-crest.png"
        favicon32x32: "oxford-crest.png"
        apple_touch_icon: "oxford-crest.png"
        theme_color: "#002147"
        msapplication_TileColor: "#002147"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Daniel Barbosa"
      icon: oxford-crest.png
      iconHeight: 48

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
